version: '3'

services:
  app:
    build: .
    depends_on: 
      - redis
    links:
      - redis
    command: yarn dev
    ports: 
      - 3000:3000
    volumes:
      - .:/urs/app
      - /urs/app/node_modules
    environment:
      NODE_ENV: dev
      PORT: 3000
  redis: 
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: 12344321